package main

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// TestServiceBridgeHydrateLMS verifies that the core-service compiler bridge
// can POST a compiled LMS course JSON payload to the lms-service internal
// hydration endpoint and receive a 200 OK response.
func TestServiceBridgeHydrateLMS(t *testing.T) {
	// Mock the lms-service internal endpoint
	mockLMS := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("expected POST, got %s", r.Method)
		}
		if r.URL.Path != "/internal/hydrate-lms" {
			t.Errorf("expected /internal/hydrate-lms, got %s", r.URL.Path)
		}
		if ct := r.Header.Get("Content-Type"); ct != "application/json" {
			t.Errorf("expected Content-Type application/json, got %s", ct)
		}

		body, err := io.ReadAll(r.Body)
		if err != nil {
			t.Fatalf("failed to read body: %v", err)
		}
		defer r.Body.Close()

		var payload map[string]interface{}
		if err := json.Unmarshal(body, &payload); err != nil {
			t.Fatalf("failed to unmarshal JSON: %v", err)
		}

		// Verify key fields exist in the payload
		if _, ok := payload["name"]; !ok {
			t.Error("expected 'name' field in payload")
		}
		if _, ok := payload["slug"]; !ok {
			t.Error("expected 'slug' field in payload")
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		json.NewEncoder(w).Encode(map[string]string{"status": "hydrated"})
	}))
	defer mockLMS.Close()

	// Simulate what the compiler bridge does: marshal a compiled LMS product and POST it
	coursePayload := map[string]interface{}{
		"name":        "Test Course",
		"slug":        "test-course",
		"description": "A test course generated by the compiler",
		"modules": []map[string]interface{}{
			{
				"title": "Module 1",
				"lessons": []map[string]interface{}{
					{"title": "Lesson 1", "slug": "lesson-1"},
					{"title": "Lesson 2", "slug": "lesson-2"},
				},
			},
		},
	}

	payloadBytes, err := json.Marshal(coursePayload)
	if err != nil {
		t.Fatalf("failed to marshal payload: %v", err)
	}

	// POST to the mock lms-service
	resp, err := http.Post(
		mockLMS.URL+"/internal/hydrate-lms",
		"application/json",
		strings.NewReader(string(payloadBytes)),
	)
	if err != nil {
		t.Fatalf("failed to POST to mock lms-service: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Errorf("expected 200 OK, got %d", resp.StatusCode)
	}

	var result map[string]string
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		t.Fatalf("failed to decode response: %v", err)
	}

	if result["status"] != "hydrated" {
		t.Errorf("expected status 'hydrated', got %q", result["status"])
	}
}

// TestServiceBridgeHydrateFunnel verifies that the core-service compiler bridge
// can POST a compiled Funnel JSON payload to the marketing-service internal
// hydration endpoint and receive a 200 OK response.
func TestServiceBridgeHydrateFunnel(t *testing.T) {
	// Mock the marketing-service internal endpoint
	mockMarketing := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			t.Errorf("expected POST, got %s", r.Method)
		}
		if r.URL.Path != "/internal/hydrate-funnel" {
			t.Errorf("expected /internal/hydrate-funnel, got %s", r.URL.Path)
		}

		body, err := io.ReadAll(r.Body)
		if err != nil {
			t.Fatalf("failed to read body: %v", err)
		}
		defer r.Body.Close()

		var payload map[string]interface{}
		if err := json.Unmarshal(body, &payload); err != nil {
			t.Fatalf("failed to unmarshal JSON: %v", err)
		}

		if _, ok := payload["name"]; !ok {
			t.Error("expected 'name' field in payload")
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		json.NewEncoder(w).Encode(map[string]string{"status": "hydrated"})
	}))
	defer mockMarketing.Close()

	funnelPayload := map[string]interface{}{
		"name":   "Test Funnel",
		"slug":   "test-funnel",
		"domain": "example.com",
		"routes": []map[string]interface{}{
			{"path": "/", "page_slug": "home"},
			{"path": "/checkout", "page_slug": "checkout"},
		},
	}

	payloadBytes, err := json.Marshal(funnelPayload)
	if err != nil {
		t.Fatalf("failed to marshal payload: %v", err)
	}

	resp, err := http.Post(
		mockMarketing.URL+"/internal/hydrate-funnel",
		"application/json",
		strings.NewReader(string(payloadBytes)),
	)
	if err != nil {
		t.Fatalf("failed to POST to mock marketing-service: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Errorf("expected 200 OK, got %d", resp.StatusCode)
	}
}
